# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export PATH="$PATH:/usr/local/share/npm/bin"
export PATH="$PATH:/usr/local/opt/ruby/bin"

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export EDITOR=vi
export VISUAL=vi

autoload -U colors && colors

alias s="git status"
alias c="git commit"
alias blame="git blame"
alias pull="git pull"
alias push="git push"

alias bower="bower --allow-root"

alias stage="git co stage"
alias live="git co live"
alias dev="git co dev"
alias master="git co master"

